name: CI

on: [push, pull_request]

jobs:
  unit_tests:
    name: Drupal Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Perform phpunit tests
      uses: ./actions/test
  behat_tests:
    name: Behat Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Perform behat tests
      uses: ./actions/behat
  nightwatch_tests:
    name: Nightwatch.js Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Perform nightwatch.js tests
      uses: ./actions/nightwatch
  code_style:
    name: Code Style Analysis
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Analyze code style
      uses: ./actions/phpcs
